### ISSUE TITLE
Duplicate printouts to console.

### ISSUE THREAD

**Issue by Scarmez** [LuisSanchez-Dev/showredeems#1]
If the script has been reloaded, the redeem mention gets put into the console for each time the script has been reloaded.

For example - I reload my scripts 5 times. The message will be put into the console 6 times for each redemption (once for initial load and 5 for each time the script has been reloaded.)

**Comment by WedgeTalon** [comment]
Here's a fix. I've moved the creation of the PubSub client into the global space, as well as the connected and reward functions. That allowed me to add in the Unload function which gets called at reload/close to cleanup and disconnect the client.

[ShowRedeems_StreamlabsSystem.zip](https://github.com/LuisSanchez-Dev/showredeems/files/5079790/ShowRedeems_StreamlabsSystem.zip)

**Comment by LuisSanchez-Dev** [comment]
@WedgeTalon  You are right, do you want to create a pull request or do you want me to update it? 😊

**Comment by WedgeTalon** [comment]
You go ahead and integrate the fix. The code I uploaded was just quick proof of fix with no care to proper formatting. :)

Thanks for this script, btw, it was just perfectly what I needed to learn to do for a script I'm working on!

**Comment by LuisSanchez-Dev** [comment]
@WedgeTalon You are welcome we are here to help.
Fixed on version 1.0.1

**Comment by tunep** [comment]
I am still getting duplicates plus `Local variable 'client' referenced before assignment` in Script Errors.
I seem to have fixed it by adding "global client" inside Init and Unload.
